all:

cliente: 
		g++ -o client.exe client.cpp -lpthread -lrt

Servidor:
		g++ -o server.exe server.cpp -lpthread -lrt

clean: 
		rm cliente Servidor /dev/shm/sem.miSemaforo /dev/shm/clientes /dev/shm/memoriaCompartida